# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/splif-sim',
                'doc_host': 'https://roshkjr.github.io',
                'git_url': 'https://github.com/roshkjr/splif-sim',
                'lib_path': 'splif_sim'},
  'syms': {'splif_sim.core': {'splif_sim.core.foo': ('core.html#foo', 'splif_sim/core.py')}}}
